# train_config.yml
name: RealESRGAN_x4_custom
model_type: RealESRGANModel
scale: 4

datasets:
  train:
    name: CustomTrain
    type: PairedImageDataset
    dataroot_gt: ../data/train_HR
    dataroot_lq: ../data/train_LR
    io_backend:
      type: disk
    gt_size: 128
    use_hflip: true
    use_rot: true
    flip_ratio: 0.5
    rotate_ratio: 0.5
    scale: 4

network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23
  num_grow_ch: 32
  scale: 4

path:
  pretrain_network_g: ~
  param_key_g: params_ema

train:
  optim_g:
    type: Adam
    lr: 2e-4
    betas: [0.9, 0.99]
  scheduler:
    type: MultiStepLR
    milestones: [50000, 100000, 200000, 300000]
    gamma: 0.5
  total_iter: 400000
  warmup_iter: -1

logger:
  print_freq: 100
  save_checkpoint_freq: 5000